# Generated by Django 5.0.6 on 2024-05-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('player_count', models.PositiveIntegerField(default=0)),
                ('staff_count', models.PositiveIntegerField(default=0)),
                ('player_payments', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('staff_payments', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
