# Generated by Django 5.0.6 on 2024-05-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('sold_tickets', models.PositiveIntegerField(default=0)),
                ('ticket_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purchased_vip_zones', models.PositiveIntegerField(default=0)),
                ('vip_zone_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
